# Generated by Django 6.0.5 on 2026-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], default='expense', max_length=20),
            preserve_default=False,
        ),
    ]
